// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBo4P9urGdAx-Jft7yFkgK8YI7BERbQJFM',
    appId: '1:86749886971:web:6c32561e22df05f7f6335e',
    messagingSenderId: '86749886971',
    projectId: 'my-fingerprint-123',
    authDomain: 'my-fingerprint-123.firebaseapp.com',
    databaseURL: 'https://my-fingerprint-123-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'my-fingerprint-123.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5CZDGMpFcIHs6azF8zFsvMW9fuiwOH2w',
    appId: '1:86749886971:android:0d3f47e16c797beaf6335e',
    messagingSenderId: '86749886971',
    projectId: 'my-fingerprint-123',
    databaseURL: 'https://my-fingerprint-123-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'my-fingerprint-123.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAB_D1mKWjM96w5Hh3ed-1Pw_aYYlA-QMg',
    appId: '1:86749886971:ios:1bf7669e1125c880f6335e',
    messagingSenderId: '86749886971',
    projectId: 'my-fingerprint-123',
    databaseURL: 'https://my-fingerprint-123-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'my-fingerprint-123.firebasestorage.app',
    iosBundleId: 'com.example.fingerprint',
  );

}